apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo-application
  namespace: nginx-argo
spec:
  project: default

  source:
    repoURL: https://github.com/deepaksoam313/Kubernetes-main.git
    targetRevision: master
    path: argomanifest
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx-argo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
